### ISSUE TITLE
Round-trip mismatch for empty ESP

### ISSUE THREAD

**Issue by metacubed** [Mutagen-Modding/Spriggit#25]
This is an edge case I ran into when developing my project. It affects the mod header information for empty mods.

1. Create a new ESP in xEdit for a known-good baseline.
   - Note that the "Record Count" in the mod header is 0, since there are no records.
   - Note that the "Next Record ID" in the mod header is 0x800.
1. Serialize the ESP into YAML with Spriggit.
   - Note that the `ModHeader` object in `ReportData.yaml` does not have `Stats`.
   - This is expected, because they have default values.
1. Deserialize the same YAML back into an ESP.
1. Check the new ESP in xEdit.
   - The "Record Count" in the mod header is changed to 1, but there are no records.
   - The "Next Record ID" in the mod header is changed to 0x801.
   - The list of masters is cleaned to remove unused masters.

Not sure if this issue report belongs in Spriggit or Mutagen.

**Comment by Noggog** [comment]
Seeing the NextRecord issue, and fixed it in Mutagen https://github.com/Mutagen-Modding/Mutagen/commit/abf555942affe1697d4c9a0e311af1833f97f441

But we should also probably set the `NextFormIDOption.NoCheck` option on the BinaryWriteParameters

Looking into the record count now

**Comment by metacubed** [comment]
I think it actually makes sense to keep the Check parameters enabled. We do want to apply changes from the ESP file over to the YAML file, and vice versa.

For example, if someone adds a new record, wouldn't the Stats need to be kept in sync? This applies to all the properties that are serialized, I think.

Fixing the underlying issue should solve the problem, right?

**Comment by metacubed** [comment]
Also added an item about the list of masters being cleaned since it is also a round-trip problem.

The root cause is that Mutagen is cleaning the list of masters when it shouldn't be touching them. The Check options are just reflecting that real change.

**Comment by Noggog** [comment]
Depends on who is in charge of enforcing the thing in question.   Like you mentioned, the masters are being cleaned.   Is this Spriggit being helpful?  Or should spriggit turn off the master check logic during translation?

These same questions apply to all the other mod header logic settings.   Should spriggit "fix" record counts if they're wrong?   What about Next FormID?  

Any of these settings it would typically be helpful for Spriggit to fix if they get out of line.  But some users might see that as taking away control from them, as they can't have an extra master as spriggit will always clean it, etc.

**Comment by Noggog** [comment]
I'm currently thinking that Spriggit should just be in the business of translating whatever is there.  It's someone else's job to clean the masters if one is extra.  Same with the counts and such.

That might be a job for Mutagen Analyzers (the next project ill be picking up)

**Comment by metacubed** [comment]
I agree with that. However, I think using `NoCheck` will have side effects.

Let's say, after serializing to YAML, someone opens the mod in CK, makes a bunch of edits, adds masters. Then does a Serialize again. Shouldn't the new masters and records get reflected in the YAML?

The other way around as well, someone adds to the master list in the YAML file. When deserializing back to ESP. those changes should be picked up, and the ESP should have a new master.

All we want to do is prevent unintentional changes, like cleaning. Other changes do need to be synced, still.

**Comment by Noggog** [comment]
> Let's say, after serializing to YAML, someone opens the mod in CK, makes a bunch of edits, adds masters. Then does a Serialize again. Shouldn't the new masters and records get reflected in the YAML?

Well, when they make edits and add masters, those will be stored in the binary esp file.  When spriggit goes to translate, they will end up in the text file because they existed in the binary file.

The goal should be that Spriggit "trusts the masters are correct as given", in both directions
