### ISSUE TITLE
Serializing/Deserializing QUST records does not save ANAM Next Alias ID (Version 0.7.0)

### ISSUE THREAD

**Issue by ra2phoenix** [Mutagen-Modding/Spriggit#32]
QUST records do not serialize their ANAM value into the yaml, so when it's rebuilt in deserialize it just scans the existing aliases to get the next value.  According to Elminster this value is important in case they deleted aliases and should be preserved, so it needs to be explicitly saved and restored.

Steps to reproduce:
Create a patch just changing some quest text in nearly any vanilla Skyrim quest. Ex: 00025185 CR02. Save to git and back to esp, and the ANAM Next Alias ID is 18, not 19 as in vanilla records.

**Comment by Noggog** [comment]
Thanks for the report!  Will see if I can get that adjusted
https://github.com/Mutagen-Modding/Mutagen/issues/490

**Comment by Noggog** [comment]
Closed with https://github.com/Mutagen-Modding/Mutagen/issues/490
