### ISSUE TITLE
Records with reflection data do not export?

### ISSUE THREAD

**Issue by ebkarlson404** [Mutagen-Modding/Spriggit#37]
Just found this tool the other day and was looking at using it as an alternative to xEdit+scripts to export the record data from ESM files.  Seems to work nicely except that it appears that it will not export records that contain reflection data.  I understand that reflection data is not well-understood at this time and its not really safe to change it, but it would still be helpful to be able to export records that contain reflection data so that other properties in the record can be altered even if we treat the reflection data as an opaque blob.

**Comment by Noggog** [comment]
I think more likely what you're running into is that Starfield isn't fully decoded, and so Spriggit is only translating what is currently defined.  
https://github.com/Mutagen-Modding/Mutagen/issues/482

Somewhat related: #39
