### ISSUE TITLE
No warning when a form type is skipped

### ISSUE THREAD

**Issue by Pickysaurus** [Mutagen-Modding/Spriggit#39]
Currently using Spriggit for the Community Patch. 

Added a new form type Package (PACK) with 4 additional records. 

Serialized the plugin. 

No errors during serialisation. The total form count is updated but the PACK forms were omitted. 

If Spriggit encounters a data type is can't decode it should throw and error and cancel the process. Had I not checked this, the mod could've been released with missing data. 

## To Replicate
- Install 0.0.6 of the Starfield Community Patch
- Merge this mod into it https://www.nexusmods.com/starfield/mods/7459?tab=files
- See that when serializing the PACK records aren't included.

**Comment by Noggog** [comment]
I think this is mostly a symptom of early days, since starfields not fully parsed https://github.com/Mutagen-Modding/Mutagen/issues/482

I think this concern will mostly be handled once things fill out, but also with #23, which will be concerned with detecting data loss during (de)serializations
