### ISSUE TITLE
Unable to configure if either .esm file or destination folder do not exist

### ISSUE THREAD

**Issue by JMPZ11** [Mutagen-Modding/Spriggit#62]
I am trying to create a new .esm from an existing set of files, but spriggit will not let me save the configuration when the target .esm doesn't exist. As a workaround I can just put a text file out there, but that seems like it shouldn't be required to setup the sync.

Also, in v 0.18.0, if the destination folder did not exist, it would be created. This made it pretty conventient to add new items as I didn't have to create the folders first.

If it would be possible to setup a sync before the folder or esm exists, it sure would be handy.

Thanks!

**Comment by Noggog** [comment]
Can you give more details?   Are you using the UI?  The CLI?   What command text did you give exactly?

**Comment by JasonJShuler** [comment]
Using the UI, apologies.
UI version 0.20.0. I used the plus to add a new sync. The file picker for the esm doesn't let you specify a non-existant file, and if you type the name of a file that doesn't exist, the box is highlighted and the save button is greyed out. As soon as I drop an empty file with the correct name, the UI updated automatically and I could save the mapping.

The window doesn't allow you to type in a folder name anymore (I think) - you much use the directory picker and must chose an existing directory. using 0.18.0, I could just copy the name of the .esm file and paste it in the folder, and spriggit would create the folder when I initiated the translation from esm -> yaml.

The auto creating folders was quite handy especially when working on a problem that involved a bunch of attempts. Half the time I try to create, name then select a new folder, I end up with "New Folder" anyway lol.

The yaml->esm with no existing esm would be pretty common I would think?

**Comment by Noggog** [comment]
Was not able to reproduce this.   But perhaps I'm misunderstanding the issue.

Here's a video of me modifying the input/output pathing where neither of the paths point to legitimate targets

https://github.com/Mutagen-Modding/Spriggit/assets/24981326/e4db6e51-11d9-45f0-91dc-3689894922af

If you're still experiencing this, or have some extra clarity on where/how exactly this is biting you, feel free to reopen!

**Comment by JasonJShuler** [comment]
Thanks, sorry too many pots lol. Yes it is resolved, thank you very much!

**Comment by Noggog** [comment]
Reproduced
![image](https://github.com/user-attachments/assets/11056e75-6f4e-4fe1-b3a1-534e6960d445)

**Comment by JMPZ11** [comment]
I was just going to update with the same findings - I get the error when using the file picker - hadn't tried pasting a path

Thanks for following up!

**Comment by Noggog** [comment]
> it won't let me exit the field

Hmm, the yellow glow just means it's unhappy... not that it's selected and you cannot exit it.  You should be able to do things like discard, or edit other fields while it's yellow.   It's just warning you that it's not in a happy state
