### ISSUE TITLE
Clarification on how strings are handles for localized files?

### ISSUE THREAD

**Issue by JasonJShuler** [Mutagen-Modding/Spriggit#63]
Spriggit UI 0.20.0, model 0.20.0, Windows.

When converting a translated esm to yaml, all the strings are embedded into the yaml in a very easy to read manner.

When you clone or copy localized records in xEdit, only one language's value is included - the current one - not ideal. Even thought both are localized..

So I attempted to use Spriggit to copy over the complete original records with all translated values. Spriggit doesn't appear to write out the strings file that I could find (and I didn't see mention in the official docs),

 and the resultant rendered esm had all the names scrambled and missing indices and whatnot. It was as if spriggit had changed the string indexes, but neglected to update the string table.
 
 Any ideas what I'm doing wrong?
 
 Thanks!

**Comment by Noggog** [comment]
Nope, it's on my side.  Thanks for the report!  Will have a fix tomorrow, most likely
