### ISSUE TITLE
Starfield Cells losing the 'Compressed' header flag with 0.20.0

### ISSUE THREAD

**Issue by JasonJShuler** [Mutagen-Modding/Spriggit#64]
Just noticed all the Starfield .esm files I've processed through Spriggit 0.20.0 had the 'Compressed' header flag stripped off of cells.

I'm not sure if this happened in previous versions. All the vanilla cells (I've encountered so far) have the compressed flag and I make a point of double checking mine do as well; but it seems Spriggit is not serializing the Compressed header flags. I double checked that it is capable of serializing some flags - not sure why this one is getting dropped.

I assume it is important, since all the vanilla ones are.

Thanks!

**Comment by Noggog** [comment]
It's a known backburner task
https://github.com/Mutagen-Modding/Mutagen/issues/235

So far been low priority, as compression is optional, and we'd need to research appropriate compression codecs to use, etc
