### ISSUE TITLE
[BUG]: Spriggit.CLI does not include the number of records

### ISSUE THREAD

**Issue by MissCorruption** [Mutagen-Modding/Spriggit#69]
When serializing a light plugin the number of records and the next FormID are not serialized correctly, they are missing from the `RecordData.yaml`. An example is [here](https://github.com/MissCorruption/QuickLootIE/blob/b4feaee6f070e15c4c0f3ff636f7824e55009c36/Source/ESP/RecordData.yaml)

This causes plugins that are de-serialized with that input to be treated as dummy plugin.
Likewise, editing the RecordData.yaml to include the `NumRecords` and `NextFormID` fields does not carry them over to the de-serialized ESP. 

The current fix is to open the ESP in xEdit, remove the ESL flag and add it again. As for NextFormID, renumber the FormIDs using xEdit to fix that as well.

**Comment by Noggog** [comment]
See if this persists in the upcoming v0.25.   Reopen if you see it after upgrading

I did a test on my end locally, and the (still unreleased) v0.25 is doing better:
![image](https://github.com/user-attachments/assets/b0525ee3-253c-4765-b64c-aa2381f9b3ed)

It is intentional that the number of records and next formID is NOT serialized into the spriggit info.  It's "derivative" data that spriggit calculates when writing the esp.   (this was to help avoid unnecessary merge collisions on unintersting data #52 #72)

**Comment by MissCorruption** [comment]
Upon closer inspection the record number was one off for my ESP, Spriggit saved it as 1, but CK then corrected it to 2

**Comment by MissCorruption** [comment]
Appreciate the concern, but my mod is open source anyway. Attached is an ESPFE that has the correct form number. Serializing & de-serializing it causes the Form Header to show 1 instead of 2, notable by CK complaining about it when loading the plugin.

As for which record isn't counting, I'm unsure. Potentially the file header itself counts as record?

It most likely is unrelated to the master style, I just assumed it was light specifically, as no other reports were made, my apologies. 
[QuickLootIE.zip](https://github.com/user-attachments/files/16665208/QuickLootIE.zip)

**Comment by Noggog** [comment]
https://github.com/Mutagen-Modding/Mutagen/issues/544

**Comment by Noggog** [comment]
Updated some of the count logic in Mutagen.  Reopen if you notice any other count desyncs!

**Comment by MissCorruption** [comment]
Looks like I'll have to bring this one up again, well. Latest project seems to have a discrepancy with form counts again.

![Image](https://github.com/user-attachments/assets/8cee492f-46dd-47cb-b4b9-fc5ab4bbb153)

Source code is on my Github
