### ISSUE TITLE
Error syncing to Mod

### ISSUE THREAD

**Issue by DJLegends1011** [Mutagen-Modding/Spriggit#70]
![image_2024-06-25_130634077](https://github.com/Mutagen-Modding/Spriggit/assets/70036572/a118e8a1-0268-4ba0-92eb-820c727b0a2b)
getting this error when working on Starfield Version of Srpiggit on version 0.24 using Spriggit.zip instead of CLI
log here [06-25-2024_13h10m18s.log](https://github.com/user-attachments/files/15975867/06-25-2024_13h10m18s.log)

**Comment by DJLegends1011** [comment]
doesn't matter if its a lite, medium or heavy master

**Comment by Noggog** [comment]
Related to the #67 issue.   `spriggit.meta` is picked up by commonly generated `.gitignore` files, and so does not get committed properly in many scenarios.   In the meantime, you'll have to unignore the entry in your `.gitignore`
`!spriggit.meta`

Next version should have that file named differently, so hopefully wont get trapped in the same way
