### ISSUE TITLE
Ignore LastModified changes upon serializing to Git at rest. 

### ISSUE THREAD

**Issue by gir489returns** [Mutagen-Modding/Spriggit#72]
This might be related to #3 and/or #23, but simply just opening saving and closing my Starfield mod in the CK and doing an ESP -> Git serialization, tons of files are changed that are usually only 1 line and it's always the LastModified field, which is of 0 use. This creates a massive logistical nightmare when trying to do code reviews, as each commit can spiral out into touching every single file on the disk.

Some of the YAMLs even contain 2 line entries, such as PersistentTimestamp and TimeStamp. I do not know why these are changing every time, if it's something I'm doing wrong, or if it's just the behavior of the CK, but having this touch so many files each commit is a headache.

**Comment by Noggog** [comment]
Yeah, will see about excluding these.  Thanks for the suggestion!
