### ISSUE TITLE
Spriggit 25 is still saving TimeStamp (and shifting elements causing file touches)

### ISSUE THREAD

**Issue by gir489returns** [Mutagen-Modding/Spriggit#74]
Related to #72

I am dropping an item I have into QASmoke, this requires touching QASmoke itself. However, it is still generating Timestamp (and PersistentTimestamp) line changes for this file.

The terminal files are also changing without anything done to the mod other than open -> save then doing a ESP -> Git conversion in Spriggit.

Here is a screenshot of my TortiseGit changes:

![image](https://github.com/user-attachments/assets/ab90ddc4-54d0-4211-87b0-05f89ec2155b)
![image](https://github.com/user-attachments/assets/f1d9ab77-62c5-4efa-9188-e8b71b96feb7)

I have included the Touched and Untouched files. All I did was, install Spriggit 25, tell it to open the old ESP file, and send it to git. Made a commit, then opened the mod again in Creation Kit, save, send it to Git again, and this was the result.

[CheatTerminal-Cheats.zip](https://github.com/user-attachments/files/16215563/CheatTerminal-Cheats.zip)

**Comment by Noggog** [comment]
The properties being randomized is a known CK issue, i believe.   It's not spriggit reordering those

I'll take a look at omitting the timestamps as well.  Do you have a picture of those, just for reference?

**Comment by gir489returns** [comment]
>Do you have a picture of those, just for reference?

![image](https://github.com/user-attachments/assets/ec1f5bdc-df28-48a3-bf2e-6c0e603198de)
