### ISSUE TITLE
Exception occured processing a weather record.

### ISSUE THREAD

**Issue by rjp311** [Mutagen-Modding/Spriggit#77]
Spriggit: 0.25
Game: Fallout 4

![image](https://github.com/user-attachments/assets/7d341742-bc10-496e-a923-c78ec98d37f1)

Error log below:
[Current.log](https://github.com/user-attachments/files/16480789/Current.log)

Let me know if/how I can get any info on the record for you, or anything else you need.

**Comment by Noggog** [comment]
Hey, thanks for the report!  Sorry for the late reply

Two things:
1)  Can you give me the esp/esm you were translating?
2)  Can you try exporting to yaml and seeing if that is able to run through?

**Comment by rjp311** [comment]
> Hey, thanks for the report! Sorry for the late reply
> 
> Two things:
> 
> 1. Can you give me the esp/esm you were translating?
> 2. Can you try exporting to yaml and seeing if that is able to run through?

![image](https://github.com/user-attachments/assets/12c32355-1388-472a-9db2-9a5415817816)

Same error with yaml. I'll ping you on Discord with the .esp as I can't send it here.

**Comment by Noggog** [comment]
Should be fixed via https://github.com/Mutagen-Modding/Mutagen.Bethesda.Serialization/commit/e8e7585a9b5f7f6cc389db5726c0479f82c9c013

Will be included in next release (hopefully soon)
